import { NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { prisma } from '../../../lib/prisma'
import { authOptions } from '../../../lib/auth'
import { sendWhatsAppMessage, sendWhatsAppTemplateMessage } from '../../../lib/whatsapp'


// Using centralized prisma

export async function POST(request: Request) {
    try {
        const session = await getServerSession(authOptions)
        if (!session || !session.user) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
        }

        const body = await request.json()
        const { dietPlanId, patientId } = body

        if (!dietPlanId || !patientId) {
            return NextResponse.json({ error: 'Diet plan ID and patient ID are required' }, { status: 400 })
        }

        const patient = await prisma.patient.findUnique({ where: { id: patientId } })
        const dietPlan = await prisma.dietPlan.findUnique({ where: { id: dietPlanId } })

        if (!patient || !dietPlan) {
            return NextResponse.json({ error: 'Patient or diet plan not found' }, { status: 404 })
        }

        const doctor = await prisma.doctor.findUnique({
            where: { id: parseInt((session.user as any).id) }
        })

        if (!doctor) {
            return NextResponse.json({ error: 'Doctor not found' }, { status: 404 })
        }

        // 1. Format the full content
        const planLines = dietPlan.planContent.split('\n')
        let formattedContent = ''
        for (const line of planLines) {
            let cleanLine = line
            if (line.startsWith('## ')) {
                cleanLine = `\n*${line.replace('## ', '').trim()}*\n`
            } else if (line.startsWith('### ')) {
                cleanLine = `\n_ ${line.replace('### ', '').trim()} _\n`
            } else if (line.startsWith('* ') || line.startsWith('- ')) {
                cleanLine = `• ${line.substring(2)}`
            }
            cleanLine = cleanLine.replace(/\*\*(.*?)\*\*/g, '*$1*')
            formattedContent += cleanLine + '\n'
        }

        const footerText = `_Generated by MediReminder AI for ${patient.name}_`
        const fullMessage = `${formattedContent}\n\n${footerText}`.substring(0, 3900)

        // 2. Try sending the full content first (Free-form)
        // This works if the 24-hour window is open
        const sendResult = await sendWhatsAppMessage(patient.mobileNumber, fullMessage, doctor.id)

        // 3. If it fails because the 24-hour window is closed, fallback to Template
        // Error code 131047 is standard for outside 24h window
        if (!sendResult.success && (sendResult.errorCode === 131047 || sendResult.error?.includes('24 hours'))) {
            console.log('🔄 Window closed, falling back to Template delivery')
            const dietGoal = dietPlan.planContent.split('\n')[0].replace('# ', '').substring(0, 100)
            
            await sendWhatsAppTemplateMessage(
                patient.mobileNumber,
                'diet_plan_share',
                [patient.name, doctor.name || 'Your Doctor', dietGoal],
                'en',
                doctor.id
            )
        }

        // Handle Guardian if available
        if (patient.guardianNumber) {
            const guardianResult = await sendWhatsAppMessage(patient.guardianNumber, `Diet Plan for ${patient.name}:\n\n${formattedContent}`.substring(0, 3900), doctor.id)
            
            if (!guardianResult.success && (guardianResult.errorCode === 131047 || guardianResult.error?.includes('24 hours'))) {
                const dietGoal = dietPlan.planContent.split('\n')[0].replace('# ', '').substring(0, 100)
                await sendWhatsAppTemplateMessage(
                    patient.guardianNumber,
                    'diet_plan_share',
                    [`${patient.name} (Guardian Copy)`, doctor?.name || 'Your Doctor', dietGoal],
                    'en',
                    doctor.id
                )
            }
        }

        return NextResponse.json({ success: true, message: 'Diet plan shared via WhatsApp Template' })
    } catch (error) {
        console.error('Error sharing diet plan:', error)
        return NextResponse.json({ error: 'Failed to share diet plan' }, { status: 500 })
    }
}
