'use client'

import React from 'react'
import { motion } from 'framer-motion'
import { 
  BellRing, 
  BrainCircuit, 
  Users, 
  Calendar, 
  History, 
  FileCheck2 
} from 'lucide-react'

const features = [
  {
    title: 'Precision Reminders',
    description: 'Auto-syncing medicine schedules directly to patient phones.',
    icon: BellRing,
    size: 'small'
  },
  {
    title: 'AI Nutrition Core',
    description: 'Clinical grade diet plans generated by Gemini 1.5 Pro.',
    icon: BrainCircuit,
    size: 'large'
  },
  {
    title: 'Patient Intelligence',
    description: 'A complete unified dashboard for every clinical metric.',
    icon: Users,
    size: 'small'
  },
  {
    title: 'Smart Flow Scheduling',
    description: 'Algorithmic booking to maximize your clinic throughput.',
    icon: Calendar,
    size: 'small'
  },
  {
    title: 'Feedback Analytics',
    description: 'Bi-directional patient communication channels.',
    icon: History,
    size: 'small'
  },
  {
    title: 'Verified Prescriptions',
    description: 'Legal, secure, and beautiful PDF exports on tap.',
    icon: FileCheck2,
    size: 'large'
  }
]

const Features = () => {
  return (
    <section id="features" className="py-32 bg-white relative overflow-hidden">
      {/* Background Mesh */}
      <div className="absolute top-1/2 left-0 w-[600px] h-[600px] bg-blue-50 rounded-full blur-[120px] -translate-x-1/2"></div>
      
      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <div className="mb-20">
          <motion.h2 
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            className="text-blue-600 font-black tracking-widest uppercase text-sm mb-4"
          >
            System Capabilities
          </motion.h2>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-5xl md:text-7xl font-black text-slate-900 tracking-tighter"
          >
            Built for the <br />
            <span className="text-slate-300">Modern Doctor.</span>
          </motion.p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.1 }}
              className={`relative p-10 rounded-[3rem] border border-white/80 bg-white/40 backdrop-blur-3xl shadow-[0_20px_50px_rgba(0,0,0,0.03)] hover:shadow-[0_20px_50px_rgba(59,130,246,0.1)] transition-all group overflow-hidden ${
                feature.size === 'large' ? 'md:col-span-2' : 'md:col-span-1'
              }`}
            >
              <div className="absolute -top-10 -right-10 w-32 h-32 bg-blue-50 rounded-full blur-3xl opacity-0 group-hover:opacity-100 transition-opacity"></div>
              
              <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center mb-8 shadow-xl shadow-blue-600/20 group-hover:scale-110 transition-transform">
                <feature.icon className="w-8 h-8 text-white" />
              </div>
              
              <h3 className="text-2xl font-black text-slate-900 mb-4">{feature.title}</h3>
              <p className="text-lg text-slate-500 leading-relaxed max-w-sm">
                {feature.description}
              </p>
              
              <div className="mt-8 flex items-center text-blue-600 font-bold text-sm space-x-2 opacity-0 group-hover:opacity-100 transition-opacity">
                <span>Learn more</span>
                <ArrowRight size={16} />
              </div>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  )
}

// Simple Arrow icon helper
const ArrowRight = ({ size }: { size: number }) => (
  <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round"><path d="m9 18 6-6-6-6"/></svg>
)

export default Features
